console.log('hello');

console.log('welcome weekend!!!!');
console.log('welcome weekend!!!!');
console.log('welcome weekend!!!!');
console.log('welcome weekend!!!!');
console.log('welcome weekend!!!!');
console.log('welcome weekend!!!!');
console.log('welcome weekend!!!!');
console.log('welcome weekend!!!!');
console.log('welcome weekend!!!!');
console.log('welcome weekend!!!!');
console.log('welcome weekend!!!!');
console.log('welcome weekend!!!!');
console.log('welcome weekend!!!!');
console.log('welcome weekend!!!!');
console.log('welcome weekend!!!!');
console.log('welcome weekend!!!!');
console.log('welcome weekend!!!!');
console.log('welcome weekend!!!!');
console.log('welcome weekend!!!!');
console.log('welcome weekend!!!!');
console.log('welcome weekend!!!!');
console.log('welcome weekend!!!!');
console.log('welcome weekend!!!!');
console.log('welcome weekend!!!!');
console.log('welcome weekend!!!!');
console.log('welcome weekend!!!!');
console.log('welcome weekend!!!!');
console.log('welcome weekend!!!!');
console.log('welcome weekend!!!!');
console.log('welcome weekend!!!!');
console.log('welcome weekend!!!!');
console.log('welcome weekend!!!!');
console.log('welcome weekend!!!!');
console.log('welcome weekend!!!!');
console.log('welcome weekend!!!!');

